import { QueueCall } from "@/components/layout/floating-queue";

// Mock data for development
const MOCK_CALLS: QueueCall[] = [
  {
    id: "call-1",
    callerName: "Marie Dubois",
    phoneNumber: "+33 1 23 45 67 89",
    waitTime: 125,
    aiStatus: "connected",
    priority: "high",
  },
  {
    id: "call-2",
    callerName: "Jean Martin",
    phoneNumber: "+33 1 98 76 54 32",
    waitTime: 85,
    aiStatus: "connected",
    priority: "medium",
  },
  {
    id: "call-3",
    callerName: "Sophie Bernard",
    phoneNumber: "+33 1 55 44 33 22",
    waitTime: 45,
    aiStatus: "connecting",
  },
  {
    id: "call-4",
    callerName: "Pierre Lefebvre",
    phoneNumber: "+33 1 11 22 33 44",
    waitTime: 20,
    aiStatus: "pending",
    priority: "low",
  },
  {
    id: "call-5",
    callerName: "Isabelle Moreau",
    phoneNumber: "+33 1 66 77 88 99",
    waitTime: 180,
    aiStatus: "connected",
    priority: "high",
  },
];

// Configuration - set USE_MOCK_DATA to false when real API is ready
const USE_MOCK_DATA = true;
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001/api";

/**
 * QueueAPI - Service layer for managing emergency call queue
 *
 * This service provides an abstraction layer between the UI and the backend API.
 * Currently uses mock data, but can be easily switched to real API calls by:
 * 1. Setting USE_MOCK_DATA to false
 * 2. Ensuring NEXT_PUBLIC_API_URL is set in environment variables
 * 3. Implementing the actual API endpoints on the backend
 */
export class QueueAPI {
  /**
   * Fetch all calls currently in the waiting queue
   *
   * @returns Promise<QueueCall[]> - Array of calls in queue
   *
   * API Endpoint: GET /queue/calls
   * Response format: { success: boolean, data: QueueCall[] }
   */
  static async getQueueCalls(): Promise<QueueCall[]> {
    if (USE_MOCK_DATA) {
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 300));
      return [...MOCK_CALLS];
    }

    try {
      const response = await fetch(`${API_BASE_URL}/queue/calls`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch queue calls: ${response.statusText}`);
      }

      const data = await response.json();
      return data.data || [];
    } catch (error) {
      console.error("Error fetching queue calls:", error);
      throw error;
    }
  }

  /**
   * Add a new call to the waiting queue
   *
   * @param call - The call to add (without id, as it will be generated by backend)
   * @returns Promise<QueueCall> - The created call with generated id
   *
   * API Endpoint: POST /queue/calls
   * Request body: Omit<QueueCall, 'id'>
   * Response format: { success: boolean, data: QueueCall }
   */
  static async addCall(
    call: Omit<QueueCall, "id">
  ): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      const newCall: QueueCall = {
        ...call,
        id: `call-${Date.now()}`,
      };
      return newCall;
    }

    try {
      const response = await fetch(`${API_BASE_URL}/queue/calls`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(call),
      });

      if (!response.ok) {
        throw new Error(`Failed to add call: ${response.statusText}`);
      }

      const data = await response.json();
      return data.data;
    } catch (error) {
      console.error("Error adding call:", error);
      throw error;
    }
  }

  /**
   * Remove a call from the waiting queue (e.g., when answered or cancelled)
   *
   * @param callId - The id of the call to remove
   * @returns Promise<void>
   *
   * API Endpoint: DELETE /queue/calls/:callId
   * Response format: { success: boolean, message: string }
   */
  static async removeCall(callId: string): Promise<void> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return;
    }

    try {
      const response = await fetch(`${API_BASE_URL}/queue/calls/${callId}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        throw new Error(`Failed to remove call: ${response.statusText}`);
      }
    } catch (error) {
      console.error("Error removing call:", error);
      throw error;
    }
  }

  /**
   * Update a call's information (e.g., AI status, priority)
   *
   * @param callId - The id of the call to update
   * @param updates - Partial call object with fields to update
   * @returns Promise<QueueCall> - The updated call
   *
   * API Endpoint: PATCH /queue/calls/:callId
   * Request body: Partial<QueueCall>
   * Response format: { success: boolean, data: QueueCall }
   */
  static async updateCall(
    callId: string,
    updates: Partial<QueueCall>
  ): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      // In real implementation, this would merge with existing data from server
      return { id: callId, ...updates } as QueueCall;
    }

    try {
      const response = await fetch(`${API_BASE_URL}/queue/calls/${callId}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(updates),
      });

      if (!response.ok) {
        throw new Error(`Failed to update call: ${response.statusText}`);
      }

      const data = await response.json();
      return data.data;
    } catch (error) {
      console.error("Error updating call:", error);
      throw error;
    }
  }

  /**
   * Get statistics about the current queue
   *
   * @returns Promise<QueueStats> - Statistics about the queue
   *
   * API Endpoint: GET /queue/stats
   * Response format: { success: boolean, data: QueueStats }
   */
  static async getQueueStats(): Promise<QueueStats> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      return {
        totalCalls: MOCK_CALLS.length,
        averageWaitTime: Math.floor(
          MOCK_CALLS.reduce((acc, call) => acc + call.waitTime, 0) /
            MOCK_CALLS.length
        ),
        aiConnected: MOCK_CALLS.filter((c) => c.aiStatus === "connected").length,
        aiConnecting: MOCK_CALLS.filter((c) => c.aiStatus === "connecting")
          .length,
        pending: MOCK_CALLS.filter((c) => c.aiStatus === "pending").length,
        highPriority: MOCK_CALLS.filter((c) => c.priority === "high").length,
      };
    }

    try {
      const response = await fetch(`${API_BASE_URL}/queue/stats`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch queue stats: ${response.statusText}`);
      }

      const data = await response.json();
      return data.data;
    } catch (error) {
      console.error("Error fetching queue stats:", error);
      throw error;
    }
  }

  /**
   * Subscribe to real-time queue updates via WebSocket
   * In the real implementation, this would establish a WebSocket connection
   *
   * @param onUpdate - Callback function called when queue is updated
   * @returns Function to unsubscribe
   *
   * WebSocket Endpoint: ws://localhost:3001/queue/subscribe
   * Message format: { type: 'update' | 'add' | 'remove', data: QueueCall | string }
   */
  static subscribeToQueueUpdates(
    onUpdate: (calls: QueueCall[]) => void
  ): () => void {
    if (USE_MOCK_DATA) {
      // In mock mode, we don't establish a real WebSocket connection
      console.log("Mock mode: WebSocket subscription not established");
      return () => console.log("Mock mode: WebSocket unsubscribed");
    }

    // Real WebSocket implementation
    const wsUrl = API_BASE_URL.replace("http", "ws");
    const ws = new WebSocket(`${wsUrl}/queue/subscribe`);

    ws.onmessage = (event) => {
      try {
        const message = JSON.parse(event.data);
        if (message.type === "update" && message.data) {
          onUpdate(message.data);
        }
      } catch (error) {
        console.error("Error parsing WebSocket message:", error);
      }
    };

    ws.onerror = (error) => {
      console.error("WebSocket error:", error);
    };

    // Return cleanup function
    return () => {
      ws.close();
    };
  }
}

// Type definitions for API responses
export interface QueueStats {
  totalCalls: number;
  averageWaitTime: number;
  aiConnected: number;
  aiConnecting: number;
  pending: number;
  highPriority: number;
}
