import { QueueCall, QueueEntry, queueEntryToQueueCall } from "@/types/queue";
import * as queueApi from "@/api/queue";
import { tokenManager } from "@/lib/token-manager";

// Mock data for development
const MOCK_CALLS: QueueCall[] = [
  {
    id: "call-1",
    callId: "mock-call-id-1",
    callerName: "Marie Dubois",
    phoneNumber: "+33 1 23 45 67 89",
    waitTime: 125,
    aiStatus: "connected",
    priority: "high",
    keywords: ["chest pain", "breathing difficulty", "unconscious"],
    emotionalState: "panic",
  },
  {
    id: "call-2",
    callId: "mock-call-id-2",
    callerName: "Jean Martin",
    phoneNumber: "+33 1 98 76 54 32",
    waitTime: 85,
    aiStatus: "connected",
    priority: "medium",
    keywords: ["accident", "bleeding", "leg injury"],
    emotionalState: "distress",
  },
  {
    id: "call-3",
    callId: "mock-call-id-3",
    callerName: "Sophie Bernard",
    phoneNumber: "+33 1 55 44 33 22",
    waitTime: 45,
    aiStatus: "connecting",
    priority: "low",
    keywords: ["fever", "nausea"],
    emotionalState: "anxious",
  },
  {
    id: "call-4",
    callId: "mock-call-id-4",
    callerName: "Pierre Lefebvre",
    phoneNumber: "+33 1 11 22 33 44",
    waitTime: 20,
    aiStatus: "pending",
    priority: "low",
    keywords: ["minor cut", "first aid"],
    emotionalState: "calm",
  },
  {
    id: "call-5",
    callId: "mock-call-id-5",
    callerName: "Isabelle Moreau",
    phoneNumber: "+33 1 66 77 88 99",
    waitTime: 180,
    aiStatus: "connected",
    priority: "high",
    keywords: ["heart attack", "collapsed", "not responding"],
    emotionalState: "panic",
  },
];

// Configuration - set USE_MOCK_DATA to false when real API is ready
const USE_MOCK_DATA = false;

/**
 * QueueAPI - Service layer for managing emergency call queue
 *
 * This service provides an abstraction layer between the UI and the backend API.
 * Currently uses mock data, but can be easily switched to real API calls by:
 * 1. Setting USE_MOCK_DATA to false
 * 2. Ensuring NEXT_PUBLIC_API_URL is set in environment variables
 * 3. Implementing the actual API endpoints on the backend
 */
export class QueueAPI {
  /**
   * Fetch all calls currently in the waiting queue
   *
   * @returns Promise<QueueCall[]> - Array of calls in queue
   *
   * API Endpoint: GET /api/v1/queue/
   * Response format: { success: boolean, data: QueueEntry[] }
   */
  static async getQueueCalls(): Promise<QueueCall[]> {
    if (USE_MOCK_DATA) {
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 300));
      return [...MOCK_CALLS];
    }

    try {
      const entries = await queueApi.listQueueEntries({ status: "WAITING" });
      // Convert backend QueueEntry to frontend QueueCall
      return entries.map(queueEntryToQueueCall);
    } catch (error) {
      console.error("Error fetching queue calls:", error);
      throw error;
    }
  }

  /**
   * Add a new call to the waiting queue
   * Note: In the real backend, calls are added automatically by the system
   * This method is kept for mock data compatibility
   *
   * @param call - The call to add (without id, as it will be generated by backend)
   * @returns Promise<QueueCall> - The created call with generated id
   */
  static async addCall(call: Omit<QueueCall, "id">): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      const newCall: QueueCall = {
        ...call,
        id: `call-${Date.now()}`,
      };
      return newCall;
    }

    // In production, calls are added automatically by the backend when a call comes in
    // This method is not needed for real implementation
    throw new Error(
      "Adding calls manually is not supported. Calls are added automatically by the system."
    );
  }

  /**
   * Remove a call from the waiting queue (mark as completed or abandoned)
   *
   * @param queueEntryId - The id of the queue entry to remove
   * @returns Promise<void>
   *
   * API Endpoint: PATCH /api/v1/queue/:queueEntryId/status
   * Note: Sets status to COMPLETED or ABANDONED
   */
  static async removeCall(queueEntryId: string): Promise<void> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return;
    }

    try {
      await queueApi.updateQueueStatus(queueEntryId, "COMPLETED");
    } catch (error) {
      console.error("Error removing call:", error);
      throw error;
    }
  }

  /**
   * Claim a call from the queue (operator takes the call)
   *
   * @param queueEntryId - The id of the queue entry to claim
   * @param operatorId - The operator claiming the call
   * @returns Promise<QueueCall> - The updated call
   *
   * API Endpoint: POST /api/v1/queue/:queueEntryId/claim
   */
  static async claimCall(queueEntryId: string, operatorId: string): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      const mockCall = MOCK_CALLS.find((c) => c.id === queueEntryId);
      return mockCall || MOCK_CALLS[0];
    }

    try {
      await queueApi.claimQueueEntry(queueEntryId, operatorId);
      const entry = await queueApi.getQueueEntry(queueEntryId);
      return queueEntryToQueueCall(entry);
    } catch (error) {
      console.error("Error claiming call:", error);
      throw error;
    }
  }

  /**
   * Update a queue entry's status
   *
   * @param queueEntryId - The id of the queue entry to update
   * @param status - The new status
   * @returns Promise<void>
   *
   * API Endpoint: PATCH /api/v1/queue/:queueEntryId/status
   */
  static async updateCallStatus(
    queueEntryId: string,
    status: "WAITING" | "CLAIMED" | "IN_PROGRESS" | "COMPLETED" | "ABANDONED"
  ): Promise<void> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return;
    }

    try {
      await queueApi.updateQueueStatus(queueEntryId, status);
    } catch (error) {
      console.error("Error updating call status:", error);
      throw error;
    }
  }

  /**
   * Update a call's information (backward compatibility method for context)
   * Note: In production, this only fetches current state as backend doesn't support arbitrary updates
   *
   * @param callId - The id of the call to update
   * @param updates - Partial call object with fields to update (only used in mock mode)
   * @returns Promise<QueueCall> - The updated call
   */
  static async updateCall(callId: string, updates: Partial<QueueCall>): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return { id: callId, ...updates } as QueueCall;
    }

    // In production, fetch the current state since the backend doesn't support arbitrary updates
    try {
      const entry = await queueApi.getQueueEntry(callId);
      return queueEntryToQueueCall(entry);
    } catch (error) {
      console.error("Error updating call:", error);
      throw error;
    }
  }

  /**
   * Get statistics about the current queue
   *
   * @returns Promise<QueueStats> - Statistics about the queue
   *
   * API Endpoint: GET /api/v1/queue/stats
   * Response format: { success: boolean, data: QueueStats }
   */
  static async getQueueStats(): Promise<QueueStats> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      return {
        totalCalls: MOCK_CALLS.length,
        averageWaitTime: Math.floor(
          MOCK_CALLS.reduce((acc, call) => acc + call.waitTime, 0) / MOCK_CALLS.length
        ),
        aiConnected: MOCK_CALLS.filter((c) => c.aiStatus === "connected").length,
        aiConnecting: MOCK_CALLS.filter((c) => c.aiStatus === "connecting").length,
        pending: MOCK_CALLS.filter((c) => c.aiStatus === "pending").length,
        highPriority: MOCK_CALLS.filter((c) => c.priority === "high").length,
      };
    }

    try {
      const stats = await queueApi.getQueueStats();
      // Transform backend stats to frontend format
      return {
        totalCalls: stats.data.total,
        averageWaitTime: Math.floor(stats.data.avgWaitTimeSeconds),
        aiConnected: stats.data.byStatus.inProgress,
        aiConnecting: stats.data.byStatus.claimed,
        pending: stats.data.byStatus.waiting,
        highPriority: stats.data.total, // Note: Backend doesn't provide priority breakdown
      };
    } catch (error) {
      console.error("Error fetching queue stats:", error);
      throw error;
    }
  }

  /**
   * Subscribe to real-time queue updates via WebSocket
   *
   * @param onUpdate - Callback function called when queue is updated
   * @returns Function to unsubscribe
   *
   * WebSocket endpoint: ws://localhost:8080/ws/queue-dashboard?token={accessToken}
   * Message types: queue:initial, queue:added, queue:updated, queue:removed
   */
  static subscribeToQueueUpdates(onUpdate: (calls: QueueCall[]) => void): () => void {
    if (USE_MOCK_DATA) {
      // In mock mode, simulate periodic updates with the mock data
      console.log("📡 Mock mode: Starting simulated queue updates");

      // Initial update
      onUpdate([...MOCK_CALLS]);

      // Simulate updates every 10 seconds
      const intervalId = setInterval(() => {
        console.log("📡 Mock mode: Simulated queue update");
        onUpdate([...MOCK_CALLS]);
      }, 10000);

      return () => {
        clearInterval(intervalId);
        console.log("📡 Mock mode: Stopped simulated queue updates");
      };
    }

    // Real WebSocket implementation
    console.log("🔌 Connecting to queue WebSocket...");

    const wsUrl = process.env.NEXT_PUBLIC_API_URL?.replace("http", "ws") || "ws://localhost:8080";
    const token = tokenManager.getAccessToken();

    if (!token) {
      console.warn("⚠️ No access token found - falling back to polling mode");
      console.info("💡 Please login to enable WebSocket real-time updates");
      // Fallback to polling
      return this.fallbackToPolling(onUpdate);
    }

    const ws = new WebSocket(`${wsUrl}/ws/queue-dashboard?token=${token}`);
    const queueData = new Map<string, QueueEntry>();

    ws.onopen = () => {
      console.log("✅ WebSocket connected to queue dashboard");
    };

    ws.onmessage = (event) => {
      try {
        const message = JSON.parse(event.data);

        switch (message.type) {
          case "queue:initial":
            // Initial load of all queue entries
            queueData.clear();
            if (Array.isArray(message.data)) {
              message.data.forEach((entry: QueueEntry) => {
                queueData.set(entry.id, entry);
              });
              const calls = Array.from(queueData.values()).map(queueEntryToQueueCall);
              onUpdate(calls);
            }
            break;

          case "queue:added":
            // New entry added to queue
            if (message.data) {
              queueData.set(message.data.id, message.data);
              const calls = Array.from(queueData.values()).map(queueEntryToQueueCall);
              onUpdate(calls);
            }
            break;

          case "queue:updated":
            // Existing entry updated
            if (message.data && queueData.has(message.data.id)) {
              queueData.set(message.data.id, message.data);
              const calls = Array.from(queueData.values()).map(queueEntryToQueueCall);
              onUpdate(calls);
            }
            break;

          case "queue:removed":
            // Entry removed from queue
            if (message.data?.id) {
              queueData.delete(message.data.id);
              const calls = Array.from(queueData.values()).map(queueEntryToQueueCall);
              onUpdate(calls);
            }
            break;

          case "queue:pong":
            // Heartbeat response
            break;

          case "queue:error":
            console.error("❌ Queue WebSocket error:", message.error);
            break;

          default:
            console.warn("⚠️ Unknown WebSocket message type:", message.type);
        }
      } catch (error) {
        console.error("❌ Error parsing WebSocket message:", error);
      }
    };

    ws.onerror = (error) => {
      console.error("❌ WebSocket error:", error);
    };

    ws.onclose = () => {
      console.log("🔌 WebSocket disconnected from queue dashboard");
    };

    // Return cleanup function
    return () => {
      if (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING) {
        ws.close();
      }
    };
  }

  /**
   * Fallback to polling when WebSocket is not available
   * @private
   */
  private static fallbackToPolling(onUpdate: (calls: QueueCall[]) => void): () => void {
    console.log("📊 Falling back to polling mode");
    const pollInterval = 5000; // Poll every 5 seconds
    let isActive = true;

    const poll = async () => {
      while (isActive) {
        try {
          const calls = await this.getQueueCalls();
          onUpdate(calls);
        } catch (error) {
          console.error("❌ Error polling queue updates:", error);
        }
        await new Promise((resolve) => setTimeout(resolve, pollInterval));
      }
    };

    poll();

    return () => {
      isActive = false;
      console.log("📊 Stopped polling mode");
    };
  }
}

// Type definitions for API responses
export interface QueueStats {
  totalCalls: number;
  averageWaitTime: number;
  aiConnected: number;
  aiConnecting: number;
  pending: number;
  highPriority: number;
}
