import {
  QueueCall,
  QueueEntry,
  queueEntryToQueueCall,
  ConnectedMessage,
  SessionTerminatedMessage,
  AITerminatedMessage,
  CallEndedMessage,
  SubscribedMessage,
  UnsubscribedMessage,
} from "@/types/queue";
import * as queueApi from "@/api/queue";
import { tokenManager } from "@/lib/token-manager";

// Mock data for development
const MOCK_CALLS: QueueCall[] = [
  {
    id: "call-1",
    callId: "mock-call-id-1",
    callerName: "Marie Dubois",
    phoneNumber: "+33 1 23 45 67 89",
    waitTime: 125,
    aiStatus: "connected",
    priority: "high",
    keywords: ["chest pain", "breathing difficulty", "unconscious"],
    emotionalState: "panic",
  },
  {
    id: "call-2",
    callId: "mock-call-id-2",
    callerName: "Jean Martin",
    phoneNumber: "+33 1 98 76 54 32",
    waitTime: 85,
    aiStatus: "connected",
    priority: "medium",
    keywords: ["accident", "bleeding", "leg injury"],
    emotionalState: "distress",
  },
  {
    id: "call-3",
    callId: "mock-call-id-3",
    callerName: "Sophie Bernard",
    phoneNumber: "+33 1 55 44 33 22",
    waitTime: 45,
    aiStatus: "connecting",
    priority: "low",
    keywords: ["fever", "nausea"],
    emotionalState: "anxious",
  },
  {
    id: "call-4",
    callId: "mock-call-id-4",
    callerName: "Pierre Lefebvre",
    phoneNumber: "+33 1 11 22 33 44",
    waitTime: 20,
    aiStatus: "pending",
    priority: "low",
    keywords: ["minor cut", "first aid"],
    emotionalState: "calm",
  },
  {
    id: "call-5",
    callId: "mock-call-id-5",
    callerName: "Isabelle Moreau",
    phoneNumber: "+33 1 66 77 88 99",
    waitTime: 180,
    aiStatus: "connected",
    priority: "high",
    keywords: ["heart attack", "collapsed", "not responding"],
    emotionalState: "panic",
  },
];

// Configuration - set USE_MOCK_DATA to false when real API is ready
const USE_MOCK_DATA = false;

/**
 * QueueAPI - Service layer for managing emergency call queue
 *
 * This service provides an abstraction layer between the UI and the backend API.
 * Currently uses mock data, but can be easily switched to real API calls by:
 * 1. Setting USE_MOCK_DATA to false
 * 2. Ensuring NEXT_PUBLIC_API_URL is set in environment variables
 * 3. Implementing the actual API endpoints on the backend
 */
/**
 * Connection state callback type
 */
export type ConnectionStateCallback = (state: {
  isConnected: boolean;
  sessionId?: string;
  error?: string;
}) => void;

/**
 * Connection event callback type
 */
export type ConnectionEventCallback = (event: {
  type: string;
  data: unknown;
  timestamp: string;
}) => void;

export class QueueAPI {
  // Shared WebSocket instance for queue dashboard
  private static ws: WebSocket | null = null;
  private static transcriptCallbacks = new Map<string, (transcript: string) => void>();
  private static wsReadyPromise: Promise<void> | null = null;
  private static wsReadyResolve: (() => void) | null = null;
  private static queueUpdateCallbacks = new Set<(calls: QueueCall[]) => void>();
  private static queueData = new Map<string, QueueEntry>();

  // Second WebSocket instance for realtime dashboard (domain events)
  private static realtimeWs: WebSocket | null = null;
  private static realtimeWsReadyPromise: Promise<void> | null = null;
  private static realtimeWsReadyResolve: (() => void) | null = null;

  // Connection state management
  private static sessionId: string | null = null;
  private static connectionStateCallbacks = new Set<ConnectionStateCallback>();
  private static connectionEventCallbacks = new Set<ConnectionEventCallback>();

  /**
   * Fetch all calls currently in the waiting queue
   *
   * @returns Promise<QueueCall[]> - Array of calls in queue
   *
   * API Endpoint: GET /api/v1/queue/
   * Response format: { success: boolean, data: QueueEntry[] }
   */
  static async getQueueCalls(): Promise<QueueCall[]> {
    if (USE_MOCK_DATA) {
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 300));
      return [...MOCK_CALLS];
    }

    try {
      const entries = await queueApi.listQueueEntries({ status: "WAITING" });
      // Convert backend QueueEntry to frontend QueueCall
      return entries.map(queueEntryToQueueCall);
    } catch (error) {
      console.error("Error fetching queue calls:", error);
      throw error;
    }
  }

  /**
   * Add a new call to the waiting queue
   * Note: In the real backend, calls are added automatically by the system
   * This method is kept for mock data compatibility
   *
   * @param call - The call to add (without id, as it will be generated by backend)
   * @returns Promise<QueueCall> - The created call with generated id
   */
  static async addCall(call: Omit<QueueCall, "id">): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      const newCall: QueueCall = {
        ...call,
        id: `call-${Date.now()}`,
      };
      return newCall;
    }

    // In production, calls are added automatically by the backend when a call comes in
    // This method is not needed for real implementation
    throw new Error(
      "Adding calls manually is not supported. Calls are added automatically by the system."
    );
  }

  /**
   * Remove a call from the waiting queue (mark as completed or abandoned)
   *
   * @param queueEntryId - The id of the queue entry to remove
   * @returns Promise<void>
   *
   * API Endpoint: PATCH /api/v1/queue/:queueEntryId/status
   * Note: Sets status to COMPLETED or ABANDONED
   */
  static async removeCall(queueEntryId: string): Promise<void> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return;
    }

    try {
      await queueApi.updateQueueStatus(queueEntryId, "COMPLETED");
    } catch (error) {
      console.error("Error removing call:", error);
      throw error;
    }
  }

  /**
   * Claim a call from the queue (operator takes the call)
   *
   * @param queueEntryId - The id of the queue entry to claim
   * @param operatorId - The operator claiming the call
   * @returns Promise<QueueCall> - The updated call
   *
   * API Endpoint: POST /api/v1/queue/:queueEntryId/claim
   */
  static async claimCall(queueEntryId: string, operatorId: string): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      const mockCall = MOCK_CALLS.find((c) => c.id === queueEntryId);
      return mockCall || MOCK_CALLS[0];
    }

    try {
      await queueApi.claimQueueEntry(queueEntryId, operatorId);
      const entry = await queueApi.getQueueEntry(queueEntryId);
      return queueEntryToQueueCall(entry);
    } catch (error) {
      console.error("Error claiming call:", error);
      throw error;
    }
  }

  /**
   * Update a queue entry's status
   *
   * @param queueEntryId - The id of the queue entry to update
   * @param status - The new status
   * @returns Promise<void>
   *
   * API Endpoint: PATCH /api/v1/queue/:queueEntryId/status
   */
  static async updateCallStatus(
    queueEntryId: string,
    status: "WAITING" | "CLAIMED" | "IN_PROGRESS" | "COMPLETED" | "ABANDONED"
  ): Promise<void> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return;
    }

    try {
      await queueApi.updateQueueStatus(queueEntryId, status);
    } catch (error) {
      console.error("Error updating call status:", error);
      throw error;
    }
  }

  /**
   * Update a call's information (backward compatibility method for context)
   * Note: In production, this only fetches current state as backend doesn't support arbitrary updates
   *
   * @param callId - The id of the call to update
   * @param updates - Partial call object with fields to update (only used in mock mode)
   * @returns Promise<QueueCall> - The updated call
   */
  static async updateCall(callId: string, updates: Partial<QueueCall>): Promise<QueueCall> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      return { id: callId, ...updates } as QueueCall;
    }

    // In production, fetch the current state since the backend doesn't support arbitrary updates
    try {
      const entry = await queueApi.getQueueEntry(callId);
      return queueEntryToQueueCall(entry);
    } catch (error) {
      console.error("Error updating call:", error);
      throw error;
    }
  }

  /**
   * Get statistics about the current queue
   *
   * @returns Promise<QueueStats> - Statistics about the queue
   *
   * API Endpoint: GET /api/v1/queue/stats
   * Response format: { success: boolean, data: QueueStats }
   */
  static async getQueueStats(): Promise<QueueStats> {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      return {
        totalCalls: MOCK_CALLS.length,
        averageWaitTime: Math.floor(
          MOCK_CALLS.reduce((acc, call) => acc + call.waitTime, 0) / MOCK_CALLS.length
        ),
        aiConnected: MOCK_CALLS.filter((c) => c.aiStatus === "connected").length,
        aiConnecting: MOCK_CALLS.filter((c) => c.aiStatus === "connecting").length,
        pending: MOCK_CALLS.filter((c) => c.aiStatus === "pending").length,
        highPriority: MOCK_CALLS.filter((c) => c.priority === "high").length,
      };
    }

    try {
      const stats = await queueApi.getQueueStats();
      // Transform backend stats to frontend format
      return {
        totalCalls: stats.data.total,
        averageWaitTime: Math.floor(stats.data.avgWaitTimeSeconds),
        aiConnected: stats.data.byStatus.inProgress,
        aiConnecting: stats.data.byStatus.claimed,
        pending: stats.data.byStatus.waiting,
        highPriority: stats.data.total, // Note: Backend doesn't provide priority breakdown
      };
    } catch (error) {
      console.error("Error fetching queue stats:", error);
      throw error;
    }
  }

  /**
   * Subscribe to real-time queue updates via WebSocket
   *
   * @param onUpdate - Callback function called when queue is updated
   * @returns Function to unsubscribe
   *
   * WebSocket endpoint: ws://localhost:8080/ws/queue-dashboard?token={accessToken}
   * Message types: queue:initial, queue:added, queue:updated, queue:removed
   */
  static subscribeToQueueUpdates(onUpdate: (calls: QueueCall[]) => void): () => void {
    if (USE_MOCK_DATA) {
      // In mock mode, simulate periodic updates with the mock data
      console.log("📡 Mock mode: Starting simulated queue updates");

      // Initial update
      onUpdate([...MOCK_CALLS]);

      // Simulate updates every 10 seconds
      const intervalId = setInterval(() => {
        console.log("📡 Mock mode: Simulated queue update");
        onUpdate([...MOCK_CALLS]);
      }, 10000);

      return () => {
        clearInterval(intervalId);
        console.log("📡 Mock mode: Stopped simulated queue updates");
      };
    }

    // Real WebSocket implementation
    const wsUrl = process.env.NEXT_PUBLIC_API_URL?.replace("http", "ws") || "ws://localhost:8080";
    const token = tokenManager.getAccessToken();

    if (!token) {
      console.warn("⚠️ No access token found - falling back to polling mode");
      console.info("💡 Please login to enable WebSocket real-time updates");
      // Fallback to polling
      return this.fallbackToPolling(onUpdate);
    }

    // Add this callback to the set of subscribers
    this.queueUpdateCallbacks.add(onUpdate);
    console.log(
      "🔌 [QUEUE] Added queue update callback. Total subscribers:",
      this.queueUpdateCallbacks.size
    );

    // Check if WebSocket is already connected or connecting
    const wsAlreadyConnected =
      this.ws &&
      (this.ws.readyState === WebSocket.OPEN || this.ws.readyState === WebSocket.CONNECTING);

    // Initialize realtime dashboard WebSocket for domain events (if not already connected)
    const isRealtimeConnected =
      this.realtimeWs &&
      (this.realtimeWs.readyState === WebSocket.OPEN ||
        this.realtimeWs.readyState === WebSocket.CONNECTING);

    if (!isRealtimeConnected) {
      this.initializeRealtimeDashboard(wsUrl);
    }

    if (wsAlreadyConnected) {
      // If already open, send the current queue data immediately
      if (this.ws!.readyState === WebSocket.OPEN && this.queueData.size > 0) {
        const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
        onUpdate(calls);
      }

      // Return cleanup function
      return () => {
        this.queueUpdateCallbacks.delete(onUpdate);

        // Close WebSocket only if no more subscribers
        if (this.queueUpdateCallbacks.size === 0) {
          if (this.ws) {
            console.log("🔌 [QUEUE] No more subscribers, closing queue WebSocket");
            this.ws.close();
          }
          if (this.realtimeWs) {
            console.log("🔌 [REALTIME] Closing realtime dashboard WebSocket");
            this.realtimeWs.close();
          }
        }
      };
    }

    console.log("🔌 [QUEUE] Creating new WebSocket connection...");
    console.log("🔍 [DEBUG] WebSocket URL:", `${wsUrl}/ws/queue-dashboard`);
    console.log("🔍 [DEBUG] Has token:", !!token);

    // Create a promise that resolves when WebSocket is ready
    // Do this BEFORE creating the WebSocket to ensure it's always available
    if (!this.wsReadyPromise) {
      this.wsReadyPromise = new Promise((resolve) => {
        this.wsReadyResolve = resolve;
      });
    }

    const ws = new WebSocket(`${wsUrl}/ws/queue-dashboard?token=${token}`);
    this.ws = ws;

    ws.onopen = () => {
      this.notifyConnectionState({
        isConnected: true,
      });
      if (this.ws === ws && this.wsReadyResolve) {
        this.wsReadyResolve();
        this.wsReadyResolve = null;
      }
    };

    ws.onmessage = (event) => {
      try {
        const message = JSON.parse(event.data);

        switch (message.type) {
          case "connection":
            this.notifyConnectionEvent({
              type: "connection",
              data: message.data || {},
              timestamp: new Date().toISOString(),
            });
            break;

          case "connected":
            if (message.data?.sessionId) {
              this.sessionId = message.data.sessionId;
              this.notifyConnectionState({
                isConnected: true,
                sessionId: message.data.sessionId,
              });
            }
            this.notifyConnectionEvent({
              type: "connected",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            break;

          case "session_terminated":
            this.notifyConnectionState({
              isConnected: false,
              error: message.data?.reason,
            });
            this.notifyConnectionEvent({
              type: "session_terminated",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            this.sessionId = null;
            break;

          case "ai_terminated":
            this.notifyConnectionEvent({
              type: "ai_terminated",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            if (message.data?.callId) {
              const entry = Array.from(this.queueData.values()).find(
                (e) => e.callId === message.data.callId
              );
              if (entry) {
                entry.status = "COMPLETED";
                this.queueData.set(entry.id, entry);
                const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
                this.queueUpdateCallbacks.forEach((callback) => callback(calls));
              }
            }
            break;

          case "call_ended":
            this.notifyConnectionEvent({
              type: "call_ended",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            if (message.data?.queueEntryId) {
              this.queueData.delete(message.data.queueEntryId);
              const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
              this.queueUpdateCallbacks.forEach((callback) => callback(calls));
            }
            break;

          case "subscribed":
            this.notifyConnectionEvent({
              type: "subscribed",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            break;

          case "unsubscribed":
            this.notifyConnectionEvent({
              type: "unsubscribed",
              data: message.data,
              timestamp: message.data?.timestamp || new Date().toISOString(),
            });
            break;

          case "queue:initial":
            this.queueData.clear();
            if (Array.isArray(message.data)) {
              message.data.forEach((entry: QueueEntry) => {
                this.queueData.set(entry.id, entry);
              });
              const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
              this.queueUpdateCallbacks.forEach((callback) => callback(calls));
            }
            break;

          case "queue:added":
            if (message.data) {
              this.queueData.set(message.data.id, message.data);
              const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
              this.queueUpdateCallbacks.forEach((callback) => callback(calls));
            }
            break;

          case "queue:updated":
            if (message.data && this.queueData.has(message.data.id)) {
              const existingEntry = this.queueData.get(message.data.id);
              const mergedEntry = { ...existingEntry, ...message.data };
              this.queueData.set(message.data.id, mergedEntry);
              const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
              this.queueUpdateCallbacks.forEach((callback) => callback(calls));
            }
            break;

          case "queue:removed":
            if (message.data?.id) {
              this.queueData.delete(message.data.id);
              const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
              this.queueUpdateCallbacks.forEach((callback) => callback(calls));
            }
            break;

          case "queue:transcript-updated":
            if (message.data?.callId && message.data?.transcript) {
              const callback = this.transcriptCallbacks.get(message.data.callId);
              if (callback) {
                callback(message.data.transcript);
              }
            }
            break;

          case "queue:call-info-updated":
            // This handler is kept for backward compatibility but the new realtime WebSocket
            // handles CallInfoUpdatedEvent via domain events
            if (message.data?.callId) {
              const entryToUpdate = Array.from(this.queueData.entries()).find(
                ([, entry]) => entry.callId === message.data.callId
              );
              if (entryToUpdate) {
                const [entryId, existingEntry] = entryToUpdate;
                const updatedEntry = {
                  ...existingEntry,
                  ...(message.data.priority && { priority: message.data.priority }),
                  ...(message.data.priorityReason && {
                    priorityReason: message.data.priorityReason,
                  }),
                  ...(message.data.chiefComplaint && {
                    chiefComplaint: message.data.chiefComplaint,
                  }),
                  ...(message.data.currentSymptoms && {
                    keySymptoms: message.data.currentSymptoms
                      .split(",")
                      .map((s: string) => s.trim()),
                  }),
                  ...(message.data.aiSummary && { aiSummary: message.data.aiSummary }),
                  ...(message.data.aiRecommendation && {
                    aiRecommendation: message.data.aiRecommendation,
                  }),
                  ...(message.data.redFlags && { redFlags: message.data.redFlags }),
                  ...(message.data.vitalSigns && { vitalSigns: message.data.vitalSigns }),
                  ...(message.data.address && { location: message.data.address }),
                  ...(message.data.city && {
                    location:
                      `${message.data.address || existingEntry.location || ""}, ${message.data.city}`
                        .trim()
                        .replace(/^,\s*/, ""),
                  }),
                  ...(message.data.patientAge && { patientAge: message.data.patientAge }),
                  ...(message.data.patientGender && { patientGender: message.data.patientGender }),
                };
                this.queueData.set(entryId, updatedEntry);
                const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
                this.queueUpdateCallbacks.forEach((callback) => callback(calls));
              }
            }
            break;

          case "queue:pong":
            break;

          case "queue:error":
            console.error("❌ [WEBSOCKET] Error:", message.error);
            this.notifyConnectionState({
              isConnected: false,
              error: message.error,
            });
            break;

          default:
            // Silently ignore unknown message types
            break;
        }
      } catch (error) {
        console.error("❌ [WEBSOCKET] Error parsing message:", error);
      }
    };

    ws.onerror = (error) => {
      // Only log if WebSocket was actually open (not a normal close during React Strict Mode)
      if (ws.readyState === WebSocket.OPEN) {
        console.error("❌ WebSocket error:", error);
        this.notifyConnectionState({
          isConnected: false,
          error: "WebSocket connection error",
        });
      }
    };

    ws.onclose = (event) => {
      // Only log abnormal closures (not React Strict Mode cleanup)
      // Code 1006 = abnormal closure, Code 1000 = normal closure
      const isAbnormal = !event.wasClean && event.code !== 1000;
      if (isAbnormal && ws === this.ws) {
        console.warn("⚠️ WebSocket disconnected unexpectedly", {
          code: event.code,
          reason: event.reason,
        });
      }

      // Only notify if this was the active WebSocket
      if (ws === this.ws) {
        this.notifyConnectionState({
          isConnected: false,
          error: isAbnormal ? event.reason || "Connection closed" : undefined,
        });
      }

      // Only clear if this is the current WebSocket instance
      if (this.ws === ws) {
        this.ws = null;
        this.wsReadyPromise = null;
        this.wsReadyResolve = null;
        this.sessionId = null;
      }
    };

    // Return cleanup function
    return () => {
      this.queueUpdateCallbacks.delete(onUpdate);
      console.log(
        "🔌 [QUEUE] Removed queue update callback. Remaining subscribers:",
        this.queueUpdateCallbacks.size
      );

      // Close WebSocket only if no more subscribers
      if (this.queueUpdateCallbacks.size === 0) {
        // Close queue dashboard WebSocket (silently during cleanup)
        if (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING) {
          ws.close();
        }
        // Only clear if this is the current WebSocket instance
        if (this.ws === ws) {
          this.ws = null;
          this.wsReadyPromise = null;
          this.wsReadyResolve = null;
          this.queueData.clear();
        }

        // Close realtime dashboard WebSocket (silently during cleanup)
        if (
          this.realtimeWs &&
          (this.realtimeWs.readyState === WebSocket.OPEN ||
            this.realtimeWs.readyState === WebSocket.CONNECTING)
        ) {
          this.realtimeWs.close();
        }
      }
    };
  }

  /**
   * Subscribe to transcript updates for a specific call
   *
   * @param callId - The call ID to subscribe to
   * @param onTranscriptUpdate - Callback function called when transcript is updated
   * @returns Function to unsubscribe
   */
  static subscribeToTranscript(
    callId: string,
    onTranscriptUpdate: (transcript: string) => void
  ): () => void {
    console.log(`📝 [TRANSCRIPT] Subscribing to transcript for call: ${callId}`);

    // Store the callback
    this.transcriptCallbacks.set(callId, onTranscriptUpdate);
    console.log(`✅ [TRANSCRIPT] Callback stored for callId: ${callId}`);

    // Function to send subscription message
    const sendSubscription = () => {
      if (this.ws && this.ws.readyState === WebSocket.OPEN) {
        const subscribeMessage = {
          type: "queue:subscribe-transcript",
          callId: callId,
        };
        console.log(
          "📤 [TRANSCRIPT] Sending subscribe message:",
          JSON.stringify(subscribeMessage, null, 2)
        );
        this.ws.send(JSON.stringify(subscribeMessage));
        console.log("✅ [TRANSCRIPT] Subscribe message sent successfully");
        return true;
      }
      return false;
    };

    // Try to send subscription immediately if WebSocket is already connected
    if (sendSubscription()) {
      console.log("✅ [TRANSCRIPT] Subscription sent immediately (WebSocket already open)");
    } else {
      // Wait for WebSocket to be ready using the promise
      console.log("⏳ [TRANSCRIPT] Waiting for WebSocket to connect...");

      // Ensure the promise exists - if not, create it (this handles race conditions)
      if (!this.wsReadyPromise) {
        console.warn("⚠️ [TRANSCRIPT] WebSocket not initialized yet. Creating ready promise...");
        this.wsReadyPromise = new Promise((resolve) => {
          this.wsReadyResolve = resolve;
        });
      }

      this.wsReadyPromise
        .then(() => {
          console.log("✅ [TRANSCRIPT] WebSocket is now ready, sending subscription");
          if (!sendSubscription()) {
            console.error("❌ [TRANSCRIPT] Failed to send subscription even after WebSocket ready");
          }
        })
        .catch((err) => {
          console.error("❌ [TRANSCRIPT] Error waiting for WebSocket:", err);
        });
    }

    // Return unsubscribe function
    return () => {
      console.log(`📝 [TRANSCRIPT] Unsubscribing from transcript for call: ${callId}`);

      // Remove the callback
      this.transcriptCallbacks.delete(callId);
      console.log(`✅ [TRANSCRIPT] Callback removed for callId: ${callId}`);

      // Send unsubscription message if WebSocket is connected
      if (this.ws && this.ws.readyState === WebSocket.OPEN) {
        const unsubscribeMessage = {
          type: "queue:unsubscribe-transcript",
          callId: callId,
        };
        console.log(
          "📤 [TRANSCRIPT] Sending unsubscribe message:",
          JSON.stringify(unsubscribeMessage, null, 2)
        );
        this.ws.send(JSON.stringify(unsubscribeMessage));
        console.log("✅ [TRANSCRIPT] Unsubscribe message sent");
      }
    };
  }

  /**
   * Initialize realtime dashboard WebSocket for domain events
   * This is a separate WebSocket connection that receives CallInfoUpdatedEvent
   * @private
   */
  private static initializeRealtimeDashboard(wsUrl: string): void {
    if (!this.realtimeWsReadyPromise) {
      this.realtimeWsReadyPromise = new Promise((resolve) => {
        this.realtimeWsReadyResolve = resolve;
      });
    }

    const realtimeWs = new WebSocket(`${wsUrl}/ws/dashboard`);
    this.realtimeWs = realtimeWs;

    realtimeWs.onopen = () => {
      // Subscribe to "queue" room to receive CallInfoUpdatedEvent
      realtimeWs.send(
        JSON.stringify({
          type: "subscribe",
          room: "queue",
        })
      );

      if (this.realtimeWs === realtimeWs && this.realtimeWsReadyResolve) {
        this.realtimeWsReadyResolve();
        this.realtimeWsReadyResolve = null;
      }
    };

    realtimeWs.onmessage = (event) => {
      try {
        const message = JSON.parse(event.data);

        switch (message.type) {
          case "connection":
          case "subscribed":
          case "pong":
            // Silently handle connection lifecycle messages
            break;

          case "event":
            if (message.event?.type === "domain_event") {
              const eventData = message.event.data;
              // Check if this is CallInfoUpdatedEvent by structure (callId + extractedData)
              if (eventData?.callId && eventData?.extractedData) {
                this.handleCallInfoUpdatedEvent(eventData);
              }
            }
            break;

          default:
            break;
        }
      } catch (error) {
        console.error("❌ [REALTIME] Error parsing message:", error);
      }
    };

    realtimeWs.onerror = (error) => {
      // Only log if WebSocket was actually open (not a normal close during React Strict Mode)
      if (realtimeWs.readyState === WebSocket.OPEN) {
        console.error("❌ [REALTIME] WebSocket error:", error);
      }
    };

    realtimeWs.onclose = (event) => {
      // Only log abnormal closures (not React Strict Mode cleanup)
      const isAbnormal = !event.wasClean && event.code !== 1000;
      if (isAbnormal && realtimeWs === this.realtimeWs) {
        console.warn("⚠️ [REALTIME] WebSocket disconnected unexpectedly", {
          code: event.code,
          reason: event.reason,
        });
      }

      // Only clear if this is the current WebSocket instance
      if (this.realtimeWs === realtimeWs) {
        this.realtimeWs = null;
        this.realtimeWsReadyPromise = null;
        this.realtimeWsReadyResolve = null;
      }
    };
  }

  /**
   * Handle CallInfoUpdatedEvent from realtime dashboard
   * @private
   */
  private static handleCallInfoUpdatedEvent(eventData: {
    callId: string;
    updatedFields: string[];
    extractedData: {
      age?: number;
      gender?: string;
      address?: string;
      city?: string;
      postalCode?: string;
      priority?: "P0" | "P1" | "P2" | "P3";
      priorityReason?: string;
      chiefComplaint?: string;
      currentSymptoms?: string;
      consciousness?: string;
    };
  }): void {
    const entryToUpdate = Array.from(this.queueData.entries()).find(
      ([, entry]) => entry.callId === eventData.callId
    );

    if (entryToUpdate) {
      const [entryId, existingEntry] = entryToUpdate;
      const extracted = eventData.extractedData;

      const updatedEntry = {
        ...existingEntry,
        ...(extracted.priority && { priority: extracted.priority }),
        ...(extracted.chiefComplaint && { chiefComplaint: extracted.chiefComplaint }),
        ...(extracted.currentSymptoms && {
          keySymptoms: extracted.currentSymptoms.split(",").map((s) => s.trim()),
        }),
        ...(extracted.address && { location: extracted.address }),
        ...(extracted.city && {
          location: `${extracted.address || existingEntry.location || ""}, ${extracted.city}`
            .trim()
            .replace(/^,\s*/, ""),
        }),
        ...(extracted.age && { patientAge: extracted.age }),
        ...(extracted.gender && { patientGender: extracted.gender }),
      };

      this.queueData.set(entryId, updatedEntry);
      const calls = Array.from(this.queueData.values()).map(queueEntryToQueueCall);
      this.queueUpdateCallbacks.forEach((callback) => callback(calls));
    }
  }

  /**
   * Fallback to polling when WebSocket is not available
   * @private
   */
  private static fallbackToPolling(onUpdate: (calls: QueueCall[]) => void): () => void {
    console.log("📊 Falling back to polling mode");
    const pollInterval = 5000; // Poll every 5 seconds
    let isActive = true;

    const poll = async () => {
      while (isActive) {
        try {
          const calls = await this.getQueueCalls();
          onUpdate(calls);
        } catch (error) {
          console.error("❌ Error polling queue updates:", error);
        }
        await new Promise((resolve) => setTimeout(resolve, pollInterval));
      }
    };

    poll();

    return () => {
      isActive = false;
      console.log("📊 Stopped polling mode");
    };
  }

  /**
   * Subscribe to connection state changes
   *
   * @param callback - Function called when connection state changes
   * @returns Function to unsubscribe
   */
  static subscribeToConnectionState(callback: ConnectionStateCallback): () => void {
    this.connectionStateCallbacks.add(callback);
    console.log(
      "🔌 [CONNECTION] Added connection state callback. Total subscribers:",
      this.connectionStateCallbacks.size
    );

    // Send initial state if connected
    if (this.ws?.readyState === WebSocket.OPEN && this.sessionId) {
      callback({
        isConnected: true,
        sessionId: this.sessionId,
      });
    }

    return () => {
      this.connectionStateCallbacks.delete(callback);
      console.log(
        "🔌 [CONNECTION] Removed connection state callback. Remaining:",
        this.connectionStateCallbacks.size
      );
    };
  }

  /**
   * Subscribe to connection events (connected, terminated, call_ended, etc.)
   *
   * @param callback - Function called when connection events occur
   * @returns Function to unsubscribe
   */
  static subscribeToConnectionEvents(callback: ConnectionEventCallback): () => void {
    this.connectionEventCallbacks.add(callback);
    console.log(
      "📡 [CONNECTION] Added connection event callback. Total subscribers:",
      this.connectionEventCallbacks.size
    );

    return () => {
      this.connectionEventCallbacks.delete(callback);
      console.log(
        "📡 [CONNECTION] Removed connection event callback. Remaining:",
        this.connectionEventCallbacks.size
      );
    };
  }

  /**
   * Get current connection state
   */
  static getConnectionState(): { isConnected: boolean; sessionId: string | null } {
    return {
      isConnected: this.ws?.readyState === WebSocket.OPEN,
      sessionId: this.sessionId,
    };
  }

  /**
   * Notify all connection state subscribers
   * @private
   */
  private static notifyConnectionState(state: {
    isConnected: boolean;
    sessionId?: string;
    error?: string;
  }) {
    this.connectionStateCallbacks.forEach((callback) => {
      try {
        callback(state);
      } catch (error) {
        console.error("❌ [CONNECTION] Error in connection state callback:", error);
      }
    });
  }

  /**
   * Notify all connection event subscribers
   * @private
   */
  private static notifyConnectionEvent(event: { type: string; data: unknown; timestamp: string }) {
    this.connectionEventCallbacks.forEach((callback) => {
      try {
        callback(event);
      } catch (error) {
        console.error("❌ [CONNECTION] Error in connection event callback:", error);
      }
    });
  }

  /**
   * Reset WebSocket state - FOR TESTING ONLY
   * @internal
   */
  static __resetForTesting() {
    if (this.ws) {
      this.ws.close();
    }
    if (this.realtimeWs) {
      this.realtimeWs.close();
    }
    this.ws = null;
    this.realtimeWs = null;
    this.transcriptCallbacks.clear();
    this.wsReadyPromise = null;
    this.wsReadyResolve = null;
    this.realtimeWsReadyPromise = null;
    this.realtimeWsReadyResolve = null;
    this.queueUpdateCallbacks.clear();
    this.queueData.clear();
    this.sessionId = null;
    this.connectionStateCallbacks.clear();
    this.connectionEventCallbacks.clear();
  }
}

// Type definitions for API responses
export interface QueueStats {
  totalCalls: number;
  averageWaitTime: number;
  aiConnected: number;
  aiConnecting: number;
  pending: number;
  highPriority: number;
}
